version: 2
updates:
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: gomod
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/backend-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: docker
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/backend-dependabot-reviewers"
    # Ignore Alpine 3.19: https://northerntech.atlassian.net/browse/QA-643
    ignore:
      - dependency-name: "docker.io/alpine"
        update-types: ["version-update:semver-major"]
